name: Quantum CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PYTHON_VERSION: "3.10"
  VENV_DIR: "./venv"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev

      - name: Create virtual environment
        run: |
          python -m venv ${{ env.VENV_DIR }}
          source ${{ env.VENV_DIR }}/bin/activate
          pip install --upgrade pip virtualenv invoke

      - name: Install dependencies
        run: |
          source ${{ env.VENV_DIR }}/bin/activate
          inv install

      - name: Run tests
        run: |
          source ${{ env.VENV_DIR }}/bin/activate
          inv test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            test-reports/junit.xml
            test-reports/coverage.xml
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: test-reports/coverage.xml